# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint & ~QtCore.Qt.WindowMinimizeButtonHint)
        self.setWindowIcon(QtGui.QIcon('icon.ico'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(397, 162)
        MainWindow.setMinimumSize(QtCore.QSize(397, 162))
        MainWindow.setMaximumSize(QtCore.QSize(397, 162))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spin_second = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_second.setObjectName("spin_second")
        self.spin_second.setMaximum(2147483647)
        self.gridLayout_2.addWidget(self.spin_second, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.output_devices = QtWidgets.QComboBox(self.centralwidget)
        self.output_devices.setObjectName("output_devices")
        self.gridLayout_2.addWidget(self.output_devices, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.output_files = QtWidgets.QComboBox(self.centralwidget)
        self.output_files.setObjectName("output_files")
        self.gridLayout_2.addWidget(self.output_files, 2, 1, 1, 1)
        self.button_save = QtWidgets.QPushButton(self.centralwidget)
        self.button_save.setObjectName("button_save")
        self.gridLayout_2.addWidget(self.button_save, 3, 0, 1, 1)
        self.button_tray = QtWidgets.QPushButton(self.centralwidget)
        self.button_tray.setObjectName("button_tray")
        self.gridLayout_2.addWidget(self.button_tray, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 397, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyAudioNoSleep"))
        self.label.setText(_translate("MainWindow", " Время опроса в секундах"))
        self.label_2.setText(_translate("MainWindow", " Устройство вывода"))
        self.label_3.setText(_translate("MainWindow", " Файл для воспроизведения"))
        self.button_save.setText(_translate("MainWindow", "Сохранить"))
        self.button_tray.setText(_translate("MainWindow", "Свернуть в трей"))
